name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'
        
    - name: Install dependencies
      run: |
        brew install create-dmg
        
    - name: List Xcode project info
      run: |
        xcodebuild -list -project AndroLaunch.xcodeproj
        
    - name: Build App
      run: |
        # Create xcodeproj if it doesn't exist
        if [ ! -d "AndroLaunch.xcodeproj" ]; then
          xcodebuild -create -scheme AndroLaunch
        fi
        
        # Build the project
        xcodebuild clean build \
          -project AndroLaunch.xcodeproj \
          -scheme AndroLaunch \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
    - name: Create DMG
      run: |
        mkdir -p dmg
        cp -r build/Build/Products/Release/AndroLaunch.app dmg/
        create-dmg \
          --volname "AndroLaunch" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "AndroLaunch.app" 200 190 \
          --hide-extension "AndroLaunch.app" \
          --app-drop-link 600 185 \
          "AndroLaunch.dmg" \
          "dmg/"
          
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: AndroLaunch.dmg
        generateReleaseNotes: true
        token: ${{ secrets.GITHUB_TOKEN }} 