name: Update Homebrew

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
    - name: Update Homebrew Cask
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        tap: alex1115alex/homebrew-tap
        formula: androlaunch
        tag: ${{ github.ref }}
        revision: ${{ github.sha }}
        force: false